### PR TITLE
Edtran/security Fix eslint

### PR DESCRIPTION
**Pull request by xTEddie**

### CODE REVIEW

**Review by grantborthwick — APPROVED** [review]
Are we running eslint on the build pipeline to prevent new issues from coming up?

**Review by shurane — APPROVED** [review]
Changes to other file are added from eslint suggestions, right? i.e. eslint any comments, `let` vs `const`?

lgtm.

**Comment by xTEddie** [comment]
@grantborthwick yes, it's part of the build pipeline

**Review by shengchenmicrosoftworkemail — APPROVED** [review]

**Comment by xTEddie** [comment]
@shurane yes, they were added from eslint suggestions

**Pull request merged**
